### ISSUE TITLE
Any chance to support stable HaXe?

### ISSUE THREAD

**Issue by singpolyma** [kevinresol/bigint#2]
Would it be very hard to support `3.4.7` with this library?

**Comment by kevinresol** [comment]
_Apparently_ `final` is the the only haxe 4 feature used. I think replacing them with the Haxe3 immutable equivalent would work.

**Comment by singpolyma** [comment]
Looks like the obvious analog for Haxe3 in this case is `static inline var` per https://stackoverflow.com/questions/25424247/constants-in-haxe

**Comment by kevinresol** [comment]
I think it is `var(default, null)`
